name: Generate Snake Game

on:
  schedule: # every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
  github_user_name: bgitesh   # <-- must be your username
  svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
